language: node_js

node_js:
  - "6"

branches:
  only:
  - develop

after_success:
  - chmod a+x ./scripts/travis-automerge.sh
  - ./scripts/travis-automerge.sh

env:
  - secure: "NOxQK3XTjWwkoIMni7+vI+2I9p4oEhS3wd2IspeTNrwxsPRQyJ90cZb/ngS3mDc4eq/oc3Y474qa8jCgPooSeeLVi39+lahaeCFNBBmSGGwofYTLRFb6kuLZYoer/nS0h9Zv0ANBU7t2DaReHs+5zlSVoTsa4nP+4I56xNMYXvS3Ec1q7kBCj5dnrfPCruEn15p8YUKkhCGP4Be0vEUIpPxEDcNNnulECevde1LzdDZjFmCROuCwZfj0RtZgaQRTnjfsoSgxA5eHpBM7RN6amH7HXSDw6depy6EGkF1sK1A5tprgNO7DvsYPa3QVS7YLPvzn1TEuaXMrK9AK3Jx1dBAlzvaQlnPwwEJeIUEZBw5DGYnipDRJxWRR36a/vUKmoVtVE4RJCb064kRgRUPNTRuCecGcVRzRmzP9izlqNtc07AyhU2sGCfm84QhJESgBKvdjrO/nrFo0vKORmS+Fa50fgcScmYamwIzl0SqkokZsJxWiz2JbmGAob17n7l2bPCVsUbIFDxdgd6EROhniKAqCoLYy6X1g8l1B20IeeH7MsLcXfMWt9RgKnkl5jVeo68i/6ZHZpTPW5LAS3IP0i9XNNFdxKILR9tM8Fxdaqip8pWS4TWrs9sm6w/dmwXiM6wD3OISIyipAW+1aOrVHlzjJilWAvF/U4GN9+l3ym0A="